[[redirects]]
  from = "/index.html"
  to = "/*"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src https:; object-src 'none'; script-src https: 'unsafe-inline'; style-src https: 'unsafe-inline'"